#+OPTIONS: toc:nil H:10
#+LaTeX_HEADER: \usepackage{cv}
#+MACRO: first  Lorenzo
#+MACRO: last   Giuliani
#+MACRO: full   {{{first}}} {{{last}}}
#+MACRO: email  [[lorenzo@giuliani.me][lorenzo@giuliani.me]]
#+MACRO: github https://github.com/zenlor
#+TITLE: Curriculum Vitae - Lorenzo Giuliani


* Personal Information
** Name
{{{full}}}

** Github
{{{github}}}

** E-mail
{{{email}}}

* Summary

#+BEGIN_QUOTE
Simplicity is a prerequisite for reliability - Edsger W. Dijkstra
#+END_QUOTE

Computer programmer, devops and security enthusiast with a keen eye towards
functional programming. Nerd that loves to harness computers powers wielding Vim
and, surprisingly, Emacs. Prefers to break down problems in small chunks to
process, be it microservices or simpler functions. Loves good technology which
makes life simple while keeps an eye on maintainability and sustainability.

* Technical Skills overview
** Languages
- Proficient :: Go, node.js, Clojure, Posix Shell
- Familiar :: Python, Java, C/C++, lisp, Zig, Rust

** Operating Systems
- Proficient :: GNU/Linux: NixOS and standard Linux distributions. Windows/MS DOS
- Familiar :: MacOS, MacOS X, AmigaOS

** Tools
- Proficient :: Linux Containers (LXC), Docker, POSIX Shell, Terraform, Ansible, nix
- Familiar :: KVM, VMWare, VirtualBox

** Platforms
- Proficient :: AWS, DigitalOcean, Scaleway
- Familiar :: OVH, generic VPS providers

* Work Experience
** Nov 2019 - Present
*Senior SRE*, Malwarebytes Inc, Perugia, Italy

- Principal SRE for Malwarebytes' EDR project based in Italy. Maintainer of the
  Infrastructure as Code for the project using Terraform over AWS. The tech
  stack is based fully on Terraform, AWS ECS, AWS Lambda, AWS SQS and lately,
  the new addition, EKS.
- Active monitoring setup over CloudWatch and SignalFX with real-time alarms for
  the older part of the infrastructure.
- Prometheus Operator setup for EKS as a future proof solution to distributed
  monitoring of thousands of containers.
- maintainer of the internal monitoring, uptime and testing tools written in Go
  and python, pushing metrics over prometheus, statsd or cloudwatch.

** May 2019 - July 2019
*Backend Developer*, Myjar ltd, Tallinn, Estonia

- Maintainer of company microservices and reimplementation of many of them to
  fix legacy bugs and issues talking to different third party providers
  and the corporate Camunda server.

** January 2016 - December 2018
*Backend Developer, Devop*, Mobilebridge BV, Amsterdam, Netherlands

- Built the service infrastructure based on Docker containers and Rancher.
  Servers are deployed on the AWS stack (EC2, ECS, Route 53, S3, CloudFront,
  RDS, Lambda, API Gateway). The focus is on high-availability, fault tolerance,
  auto-scaling, speed and ease of deployment.
- Developed an internal distributed api stress testing tool with built-in
  autoscaling (over AWS EC2) and workload distribution.
- Developed and maintain the real time event processing pipeline based on
  serverless Lambda functions, currently in beta phase.

** April 2013 - November 2015
*Backend node.js developer*, Contentment, London, United Kingdom

- Lead backend developerfor the main publishing product Padify. Refactor
  business logic moving from MongoDB to PostgreSQL while developing features,
  mainly export created publications to multiple formats from pdf to epubs
- Move to a microservice architecture deployed over AWS ECS and Heroku.
- Set up content optimization pipeline for static assets deployed over S3.
- Enhanced security of the tech stack thru security assessment and penetration testing.
- Languages: Javascript on Node.js, Go, Python, shell
- Tech stack: Linux, HTML5, Express.js, Mongoose, MongoDB, PostgreSQL, NGiNX,
  Linux Containers based on Docker, nmap, wireshark.

** March 2007 - Present
*Core developer*, GtGames, L'Aquila, Italy

Currently only maintaining remaining services.

- Machete CMS, a fast content management system developed in Ruby and Node.js.
- Managed servers for deployment of the CMS, mail system and domain management.
- Developed a set of sensible Javascript UI widgets based on lightweight
  functional libraries, avoiding the weight of bigger libraries like jQuery.
- Languages: Ruby, Javascript, Python, Java, shell
- Tech stack: Linux, HTML5, Sinatra & Padrino, Flask, NGiNX, PostgreSQL,
  MongoDB, CouchDB, Linux Containers based on cgroups, nmap, wireshark.

** January 2009 - December 2009
*Software developer*, Unbit SAS, Torino, Italy

- Backend development for various backends powered by DJango and Flask python frameworks.
- Maintained the uWSGI-Rack (ruby) compatability layer.
- Languages: Python, Ruby, Javascript, shell
- Tech stack: Linux, Javascript, HTML, jQuery, Django, Flask, PostgreSQL, MySQL.
